# Generated by Django 4.0.3 on 2022-03-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('BannerImage', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rockstars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('LinkedIn', models.URLField(null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Image', models.CharField(max_length=255, null=True)),
                ('TribeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribe.tribes')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Image', models.CharField(max_length=255, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedAt', models.DateTimeField(auto_now=True)),
                ('ThumbnailImage', models.CharField(max_length=255, null=True)),
                ('Viewcount', models.PositiveIntegerField(default=0)),
                ('RockstarId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribe.rockstars')),
                ('TribeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribe.tribes')),
            ],
        ),
    ]
