# Generated by Django 4.0.3 on 2022-03-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondemandrequests',
            name='Name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
