# Generated by Django 3.2.12 on 2022-04-13 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='Rockstar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribe.rockstars'),
        ),
        migrations.AlterField(
            model_name='podcasts',
            name='Tribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribe.tribes'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Tribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tribe.tribes'),
        ),
    ]
