# Generated by Django 3.2.12 on 2022-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0002_ondemandrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondemandrequests',
            name='PhoneNumber',
            field=models.CharField(max_length=254),
        ),
    ]
