# Generated by Django 3.2.12 on 2022-04-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0002_ondemandrequests_name'),
        ('tribe', '0003_alter_ondemandrequests_phonenumber'),
    ]

    operations = [
    ]
