# Generated by Django 3.2.12 on 2022-04-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0003_auto_20220413_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PodcastEpisode',
            new_name='PodcastEpisodes',
        ),
    ]
