# Generated by Django 4.0.3 on 2022-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0004_rename_podcastepisode_podcastepisodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='Viewcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
