# Generated by Django 3.2.12 on 2022-04-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0006_auto_20220406_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='TribeId',
            new_name='Tribe',
        ),
        migrations.RenameField(
            model_name='podcasts',
            old_name='TribeId',
            new_name='Tribe',
        ),
        migrations.RenameField(
            model_name='rockstars',
            old_name='TribeId',
            new_name='Tribe',
        ),
    ]
