# Generated by Django 3.2.12 on 2022-04-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribe', '0007_auto_20220407_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='RockstarId',
            new_name='Rockstar',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='TribeId',
            new_name='Tribe',
        ),
    ]
